# Generated by Django 5.0.6 on 2024-07-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'DOCTOR'), ('P', 'PETIENT')], max_length=4, null='true'),
            preserve_default='true',
        ),
    ]
